version: "3.8"
services:
  postgres:
    image: postgres:13.21
    environment:
      POSTGRES_DB: takingdb
      POSTGRES_PASSWORD: D0us5xm4
    volumes:
      - pgdata:/var/lib/postgresql@13/data
    ports:
      - "5432:5432"

  quarkus-backend:
    build: 
      context: ./backend-app
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/takingdb
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: D0us5xm4

  angular-frontend:
    build:
      context: ./frontend-app
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - quarkus-backend

volumes:
  pgdata: